Refactor Checking to Rules
vhdl-linter/vhdl-linter pull request #123
Opened 2022-11-05 11:17 UTC by g0t00

Checkers now got individual files, are now called rules.
Diagnostic now shows the rule that triggered the diagnostic.
The magic comments follow now more closecly the style of eslint. Individual rules can be enabled/disabled. (Somebody should maybe write a short text about this ;))

2022-11-05 11:18 UTC, g0t00 commented
@Nik-Sch I probably should completly remove the reset checker, I would assume that it is completely mangled? It has no test cases at all.

2022-11-08 10:18 UTC, Nik-Sch requested changes
The rules currently are randomly plural or singular. This should be made coherent. I would say singular is more intuitive in the disable magic comment.
Additionally, all disable magic comments in the test files should be made to explicitly disable one message type. (e.g. `test_error_expected/01/test_no_written.vhd:3`)

2022-11-08 10:18 UTC, Nik-Sch commented on lib/parser/parser.ts
> +              new OIRange(this.file, new OI(this.file, lineNumber, 0), new OI(this.file, lineNumber, line.length - 1)),
```suggestion
              new OIRange(this.file, new OI(this.file, lineNumber, 0), new OI(this.file, lineNumber, line.length)),
```
When messages are created with a range of `getRangeToEndLine` it is not correctly disabled.
An additional test for this:
```vhdl
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity test_procedure_call is
end entity;

architecture rtl of test_procedure_call is
begin
  process
    procedure p(a : in std_ulogic; b: out std_ulogic) is
    begin
      b <= a;
    end procedure;
  begin
    p(a => '1', 32); -- vhdl-linter-disable-line instantiation
  end process;

end architecture;
```

2022-11-08 11:10 UTC, g0t00 commented on lib/parser/parser.ts
> +        } else if ((innerMatch = match[2].match(/-disable-next-line(?:\s|$)(.+)?/i)) !== null) {// TODO: next nonempty line
Who put that TODO there?

2022-11-08 13:11 UTC, Nik-Sch commented on lib/parser/parser.ts
> +        } else if ((innerMatch = match[2].match(/-disable-next-line(?:\s|$)(.+)?/i)) !== null) {// TODO: next nonempty line
It probably has been there for a long time xD

2022-11-08 14:27 UTC, g0t00 commented on lib/parser/objects.ts
>  }
Yes, the parameter thing is currently not used. But I have some other ideas for other magic comment types (setting the configuration). For which I like having a OMagicComment base type... I would prefer to keep this.

2022-11-08 14:32 UTC, Nik-Sch approved these changes
Seems good to me now

2022-11-08 15:12 UTC, merged