Refactor Read/References
vhdl-linter/vhdl-linter pull request #167
Opened 2022-12-04 12:51 UTC by g0t00

2023-01-02 15:24 UTC, Nik-Sch requested changes

2023-01-02 15:24 UTC, Nik-Sch commented on lib/parser/rules.bnf
> +expression ::= condition_operator primary
These rules are not used in the expression parser and are not relevant imo. Delete the file?

2023-01-02 15:24 UTC, Nik-Sch commented on lib/parser/statement-body-parser.ts
> +    let architecture;
rename:
```suggestion
    let statementBody;
```

2023-01-02 15:24 UTC, Nik-Sch commented on test/mixin.ts
> +// Needed for all mixins
This has nothing to do with the vhdl-linter?

2023-01-15 13:00 UTC, g0t00 commented on lib/parser/concurrent-statement-parser.ts
> +      // TODO: Build test case for nested elsif generate
I think this is out of scope.

2023-01-15 13:01 UTC, g0t00 commented on lib/parser/concurrent-statement-parser.ts
> +      // TODO: Build test case for nested elsif generate
This will become a separate issue automatically.

2023-01-15 13:04 UTC, g0t00 commented on test/test_files/test_no_error/10_expression/_test_selected_name.vhd
> +use std.textio.all ;
Not really. The point is to test more complex record types. Added some explanation.

2023-01-15 13:08 UTC, g0t00 commented on test/test_files/test_no_error/01/for_test.vhd
> +    a : for i in foo'range loop
Added description.

2023-01-17 10:49 UTC, g0t00 commented on lib/parser/objects.ts
> +  // TODO: Change constants to constant without breaking stuff
Hm, seems old? removed

2023-01-17 10:49 UTC, g0t00 commented on lib/parser/expression-parser.ts
> +          }
Added a comment.

2023-01-17 10:53 UTC, g0t00 commented on lib/parser/association-list-parser.ts
>          }
Added comments. Clear now?

2023-01-17 11:52 UTC, merged