Semantic
vhdl-linter/vhdl-linter pull request #260
Opened 2023-02-12 14:02 UTC by g0t00

2023-02-13 16:42 UTC, Nik-Sch requested changes
The project parser is constantly re initializing on edits and the whole linter is unbearable slow in larger projects...

2023-02-15 12:27 UTC, g0t00 commented
@Nik-Sch Ignore that last review request that was not on purpose

2023-02-15 19:20 UTC, Nik-Sch requested changes
I like the idea with a linter mananger but it needs thorough changes and I believe a lot of languageFeatures (maybe all except the semantic tokens) need to prefer old linters

2023-02-15 19:20 UTC, Nik-Sch commented on lib/vhdl-linter.ts
> +  elaborated = false;
This is never set to true...

2023-02-20 14:11 UTC, Nik-Sch approved these changes

2023-02-20 15:12 UTC, merged