use expression parser for concurrent_selected_signal_assignment #258
vhdl-linter/vhdl-linter pull request #323
Opened 2023-02-27 22:40 UTC by g0t00

2023-03-01 20:34 UTC, Nik-Sch requested changes

2023-03-01 20:34 UTC, Nik-Sch commented on test/test_files/test_error_expected/misc/test_with3.vhd
> +begin
formatting

2023-03-01 20:34 UTC, Nik-Sch commented on test/test_files/test_error_expected/misc/test_with4.vhd
> +
formatting

2023-03-01 20:34 UTC, Nik-Sch commented on test/test_files/test_no_error/misc/_test_with_seq.vhd
> +
formatting

2023-03-01 20:34 UTC, Nik-Sch commented on test/test_files/test_error_expected/misc/test_with4.vhd
> +		with a select b <=                  -- constant can not be written
same as test_with3?

2023-03-05 20:31 UTC, g0t00 commented on test/test_files/test_error_expected/misc/test_with4.vhd
> +		with a select b <=                  -- constant can not be written
No this is seq with3 is concurrent

2023-03-08 21:12 UTC, Nik-Sch approved these changes

2023-03-10 08:57 UTC, merged