Introduced External Name parsing, removed ORead
vhdl-linter/vhdl-linter pull request #327
Opened 2023-02-28 11:31 UTC by g0t00

2023-02-28 15:31 UTC, Nik-Sch requested changes

2023-02-28 15:31 UTC, Nik-Sch commented on lib/parser/objects.ts
> +  // This avoid false positives
```suggestion
  // This avoids false positives
```
which kind of false positives?

2023-02-28 15:31 UTC, Nik-Sch commented on lib/parser/interfaces.ts
> +  referenceLinks: O.OName[];
```suggestion
  nameLinks: O.OName[];
```
Don't know about that...

2023-02-28 15:31 UTC, Nik-Sch commented on lib/languageFeatures/completion.ts
> +  if (completionObject instanceof O.OSelectedName  || completionObject instanceof O.OSelectedName) {
```suggestion
  if (completionObject instanceof O.OSelectedName) {
```

2023-02-28 15:31 UTC, Nik-Sch commented on lib/languageFeatures/semanticToken.ts
> +    const modifiers = (obj as O.OName).write ? [SemanticTokenModifiers.modification] : [];
why is the `as` allowed?
```suggestion
    const modifiers = (obj instance of O.OName && obj.write) ? [SemanticTokenModifiers.modification] : [];
```

2023-02-28 15:31 UTC, Nik-Sch commented on lib/parser/objects.ts
> +export class OFormalReference extends OName {
```suggestion
export class OFormaName extends OName {
```

2023-02-28 15:31 UTC, Nik-Sch commented on lib/rules/ruleUnused.ts
> +      if ((port.direction === 'in' || port.direction === 'inout') && references.filter(token => token.write !== true).length === 0) {
```suggestion
      if ((port.direction === 'in' || port.direction === 'inout') && references.filter(token => token.write === false).length === 0) {
```

2023-02-28 15:31 UTC, Nik-Sch commented on lib/rules/ruleUnused.ts
> +          if (generic.referenceLinks.filter(token => token.write !== true).length === 0) {
```suggestion
          if (generic.referenceLinks.filter(token => token.write === false).length === 0) {
```

2023-02-28 15:31 UTC, Nik-Sch commented on lib/rules/ruleUnused.ts
> +            if (references.filter(token => token.write !== true).length === 0) {
```suggestion
            if (references.filter(token => token.write === false).length === 0) {
```

2023-02-28 15:31 UTC, Nik-Sch commented on lib/rules/ruleUnused.ts
> +            if (references.filter(token => token.write !== true).length === 0) {
```suggestion
            if (references.filter(token => token.write === false).length === 0) {
```

2023-02-28 15:31 UTC, Nik-Sch commented on lib/rules/ruleUnused.ts
> +            if (references.filter(token => token.write !== true).length === 0) {
```suggestion
            if (references.filter(token => token.write === false).length === 0) {
```

2023-02-28 15:31 UTC, Nik-Sch commented on test/test_files/test_no_error/misc/test_postponed.vhd
> +    c <= c;
?

2023-03-03 08:45 UTC, g0t00 commented on lib/languageFeatures/semanticToken.ts
> +    const modifiers = (obj as O.OName).write ? [SemanticTokenModifiers.modification] : [];
Why should it be?

2023-03-03 08:46 UTC, g0t00 commented on test/test_files/test_no_error/misc/test_postponed.vhd
> +    c <= c;
This is a multi driver error (I randomly found with vsim)

2023-03-03 11:35 UTC, Nik-Sch commented on lib/languageFeatures/semanticToken.ts
> +    const modifiers = (obj as O.OName).write ? [SemanticTokenModifiers.modification] : [];
Ah nvm, should be fine

2023-03-05 20:22 UTC, g0t00 commented on test/test_files/test_error_expected/external_names/test_external_names4.vhd
> +    report to_string( << INVALID .test_toplevel.apfel : std_logic_vector(5 downto 0) >> );  -- invalid kind
No. This Invalid external name kind is on different line. This did have different error inbetween and is regression test for this.

2023-03-05 20:28 UTC, g0t00 commented
@Nik-Sch I tried to organize objects and interfaces a bit. removed all references to the word reference except for OContextReference which is a name from LRM. Can you look that over?

2023-03-08 21:40 UTC, Nik-Sch approved these changes
There are still some conversations open concerning the checks of the `write` boolean of `OName`.

2023-03-08 21:40 UTC, Nik-Sch commented on lib/parser/objects.ts
> +  aliasLinks: never[] = []; // Not used. (Because recursive aliases are not allowed)
```suggestion
  aliasLinks: never[] = []; // recursive aliases are not allowed
```

2023-03-11 19:46 UTC, Nik-Sch approved these changes
The file of `elaborateReferences` should be renamed to `elaborateNames`

2023-03-11 19:46 UTC, Nik-Sch commented on lib/parser/expressionParser.ts
> +  splitBuffer(buffer: OLexerToken[], formal: boolean, write: boolean, aggregate: boolean, choice: boolean): O.OName[] {
The `aggregate` parameter doesn't make sense now and is not used. Remove it

2023-03-11 19:46 UTC, Nik-Sch commented on lib/parser/expressionParser.ts
> +          const choice = aggregate && breakToken === '=>';
`aggregate` here should be renamed to choice now

2023-03-11 19:46 UTC, Nik-Sch commented on test/unitTests/elaborate/elaborate.test.ts
> +  expect(choice?.definitions.length).toBeGreaterThan(0);
This should be equal 1 and not greater than 0. If it is not the case, just add a todo?

2023-03-11 19:46 UTC, Nik-Sch commented on test/test_files/test_no_error/references/funky_aggregate.vhd
> +  foo <= (elem => 5);                   -- TODO: Aggregates for records from not used packages throw an error.
```suggestion
  foo <= (elem => 5);                   -- TODO: elaborate choices of aggregates for records from not used packages to not throw an error.
```

2023-03-11 20:00 UTC, merged